version: '3'
services:
  server:
    build: .
    container_name: 'server'
    network_mode: bridge
    volumes:
      - .:/app
      - ./utils/developer-challange-1bf4eca39862.json:/usr/local/credentials.json
    working_dir: /app
    ports:
      - 5000:5000
    command: >
      sh -c "pip install -r requirements.txt
      && python app.py"
